CREATE TABLE usuarios (
                          id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          nome VARCHAR2(100) NOT NULL,
                          cpf VARCHAR2(14) NOT NULL UNIQUE,
                          email VARCHAR2(100) NOT NULL UNIQUE,
                          senha VARCHAR2(255) NOT NULL,
                          saldo NUMBER(15, 2) DEFAULT 0.00
);

CREATE TABLE movimentacoes (
                               id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               usuario_id NUMBER NOT NULL,
                               descricao VARCHAR2(255) NOT NULL,
                               valor NUMBER(15, 2) NOT NULL,
                               data TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                               FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);

CREATE INDEX idx_usuario_cpf ON usuarios (cpf);
CREATE INDEX idx_usuario_email ON usuarios (email);
CREATE INDEX idx_movimentacao_usuario ON movimentacoes (usuario_id);